version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sourabh_github_200626Project
  gitServerName: srcCtrl_github_Sourabh
  gitUrl: https://github.com/sourabh-harkawat-0058QC744
  gitUsername: sourabh-harkawat-0058QC744
  gitBranch: main
- name: LowerFSPackage
  gitServerName: srcCtrl_github_Sourabh
  gitUrl: https://github.com/sourabh-harkawat-0058QC744
  gitUsername: sourabh-harkawat-0058QC744
  gitBranch: testbranch
services:
- serviceName: project.sourabh_github_200626.integrations:gcfcg
  packages:
  - name: Sourabh_github_200626Project
    version: "1.0"
  - name: LowerFSPackage
    version: "2.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2106
